### PR TITLE
update packages and dependency to 3.1

### PR DESCRIPTION
**Pull request by EngRajabi**
update packages and dependency to 3.1

### CODE REVIEW

**Comment by EngRajabi** [comment]
@jbogard

**Comment by EngRajabi** [comment]
@lbargaoanu

**Comment by lbargaoanu** [comment]
We don't need app core for anything. We target .net standard 2.0 for the wider reach.

**Comment by EngRajabi** [comment]
https://dotnet.microsoft.com/platform/support/policy/dotnet-core
dotnet 2.0, 2.1, 2.2, 3.0 end of life. but 3.1 lts

**Comment by jbogard** [comment]
This isn’t necessary, netstandard2.0 is compatible with netcore2.0 *and above*.

**Pull request closed without merging**
