### PR TITLE
Strong naming

### PR DESCRIPTION
**Pull request by jbogard**
Based on MS guidance https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

### CODE REVIEW

**Comment by jbogard** [comment]
Fixes #75

**Comment by lbargaoanu** [comment]
But AM itself doesn't have a string name, right? :)

**Comment by jbogard** [comment]
Yep it does. Just none of the extensions.

**Comment by lbargaoanu** [comment]
OK, I see it does :)

**Pull request merged**
